# Generated by Django 5.2.1 on 2025-11-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_default_movement_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock minimal'),
        ),
    ]
