# Generated by Django 5.2.1 on 2025-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Code-barres'),
        ),
    ]
