# Generated by Django 5.2.1 on 2025-11-21 14:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Client')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_item', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
            },
        ),
    ]
