# Generated by Django 5.2.1 on 2025-11-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_saleitem_scan_code_saleitem_scanned_at_salescan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['position', 'id'], 'verbose_name': 'ligne de vente', 'verbose_name_plural': 'lignes de vente'},
        ),
        migrations.AddField(
            model_name='saleitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='line_type',
            field=models.CharField(choices=[('product', 'Produit'), ('note', 'Note'), ('section', 'Section')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product'),
        ),
    ]
