# Generated by Django 5.2.8 on 2025-11-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.site'),
        ),
    ]
