# Generated by Django 5.2.1 on 2025-11-23 14:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_manual_transfer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Cloture')], default='open', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='inventory.site')),
            ],
            options={
                'verbose_name': 'inventaire physique',
                'verbose_name_plural': 'inventaires physiques',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('value_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='inventory.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycountsession')),
            ],
            options={
                'verbose_name': "ligne d'inventaire",
                'verbose_name_plural': "lignes d'inventaire",
                'ordering': ['product__name'],
                'unique_together': {('session', 'product')},
            },
        ),
    ]
