# Generated by Django 5.2.1 on 2026-01-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventorycountsession_inventorycountline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssetJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('single', 'Cible unique'), ('batch', 'Lot')], default='batch', max_length=12)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('running', 'En cours'), ('success', 'Terminé'), ('failed', 'Erreur')], default='queued', max_length=12)),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Total produits')),
                ('processed_products', models.PositiveIntegerField(default=0, verbose_name='Produits traités')),
                ('force_description', models.BooleanField(default=False, verbose_name='Forcer description')),
                ('force_image', models.BooleanField(default=False, verbose_name='Forcer image')),
                ('description_changed', models.BooleanField(default=False, verbose_name='Description modifiée')),
                ('image_changed', models.BooleanField(default=False, verbose_name='Image modifiée')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('last_message', models.TextField(blank=True, verbose_name='Dernier message')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_jobs', to='inventory.product')),
            ],
            options={
                'verbose_name': "job d'enrichissement",
                'verbose_name_plural': "jobs d'enrichissement",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAssetJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.productassetjob')),
            ],
            options={
                'verbose_name': 'ligne de journal IA',
                'verbose_name_plural': 'lignes de journal IA',
                'ordering': ['created_at'],
            },
        ),
    ]
