# Generated by Django 5.2.1 on 2026-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_product_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="datasheet_fetched_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fiche technique rÃ©cupÃ©rÃ©e"
            ),
        ),
    ]
