# Generated by Django 5.1.3 on 2026-01-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_alter_product_datasheet_fetched_at"),
        ("inventory", "0021_product_pending_image"),
    ]

    operations = []
