# Generated by Django 5.2.1 on 2026-01-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_product_pending_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_is_placeholder",
            field=models.BooleanField(
                default=False, verbose_name="Image de substitution"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pending_image_is_placeholder",
            field=models.BooleanField(
                default=False, verbose_name="Aperçu image de substitution"
            ),
        ),
    ]
