# Generated by Django 5.1.3 on 2026-01-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_merge_20260129_1714"),
        ("inventory", "0022_product_image_is_placeholder_and_more"),
    ]

    operations = []
