# Generated by Django 5.2.1 on 2026-01-31 22:05

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_product_image_is_placeholder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="long_description",
            field=models.TextField(blank=True, verbose_name="Description longue"),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Description courte"),
        ),
        migrations.AddField(
            model_name="product",
            name="tech_specs_json",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Fiche technique (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="video_links",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Liens vidéo",
            ),
        ),
        migrations.AddField(
            model_name="productassetjob",
            name="asset_changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Modifications IA",
            ),
        ),
        migrations.AddField(
            model_name="productassetjob",
            name="assets",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Assets demandés",
            ),
        ),
        migrations.AddField(
            model_name="productassetjob",
            name="force_blog",
            field=models.BooleanField(default=False, verbose_name="Forcer blog"),
        ),
        migrations.AddField(
            model_name="productassetjob",
            name="force_pdf",
            field=models.BooleanField(
                default=False, verbose_name="Forcer brochures PDF"
            ),
        ),
        migrations.AddField(
            model_name="productassetjob",
            name="force_techsheet",
            field=models.BooleanField(
                default=False, verbose_name="Forcer fiche technique"
            ),
        ),
        migrations.AddField(
            model_name="productassetjob",
            name="force_videos",
            field=models.BooleanField(default=False, verbose_name="Forcer vidéos"),
        ),
        migrations.CreateModel(
            name="ProductAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("description", "Description"),
                            ("specs", "Fiche technique"),
                            ("pdf", "Brochure PDF"),
                            ("video", "Vidéo"),
                            ("blog", "Blog"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("approved", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="products/assets"
                    ),
                ),
                ("text_content", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset IA",
                "verbose_name_plural": "assets IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductBrochure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titre"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="Source")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="products/brochures",
                        verbose_name="Brochure (PDF)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brochures",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "brochure PDF",
                "verbose_name_plural": "brochures PDF",
                "ordering": ["-created_at"],
            },
        ),
    ]
