# Generated by Django 5.1.3 on 2026-01-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_merge_20260131_2216"),
        (
            "inventory",
            "0023_product_long_description_product_short_description_and_more",
        ),
    ]

    operations = []
