# Generated by Django 5.1.3 on 2026-01-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_merge_20260131_2318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="datasheet_fetched_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fiche technique récupérée"
            ),
        ),
    ]
