# Generated by Django 5.2.1 on 2026-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_subcategory_and_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorycountline",
            name="counted_qty",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
