# Generated by Django 5.2.1 on 2026-07-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_alter_inventorycountline_counted_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycountline",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventorycountsession",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_sessions",
                to="inventory.brand",
            ),
        ),
        migrations.AddField(
            model_name="inventorycountsession",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_sessions",
                to="inventory.category",
            ),
        ),
    ]
