# Generated by Django 5.2.1 on 2026-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_inventorycountline_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorycountsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Ouvert"),
                    ("closed", "Cloture"),
                    ("cancelled", "Annulé"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
